export const HOMEPAGE = "/";
export const MAPS = "/maps";
export const SIGNUPPAGE = "/auth/signup";
export const LOGINPAGE = "/auth/login";
export const PROTECTEDPAGE = "/protected";
export const NEWCUSTUMER = "/new-custumer";
export const NEWMP ="/new-mp";
export const NEWPRODUCT ="/new-product";
export const NEWPACKAGE ="/new-package";
export const NEWORDER ="/new-order";
export const SEEALLORDERS ="/get-allorders";
export const SEEALLMP="/get-allmp";
export const SEEALLPRODUCTS="/get-products";
export const SEEALLPACKAGES="/get-allpackages";
export const SEEORDERDETAIL="/order/:id";
export const SEEPRODUCTDETAIL="/product/:id";
export const SEECALENDAR="/dates";
export const NEWROUTE="/new-route";
export const SEEROUTEDETAIL="/route-detail/:id"