export const HOMEPAGE = "/regishome";
export const HomePageInfo ="/"
export const MAPS = "/maps";
export const SIGNUPPAGE = "/auth/signup";
export const LOGINPAGE = "/auth/login";
export const NEWCUSTUMER = "/new-custumer";
export const SEEALLCUSTUMER="/get-allcustumer";
export const SEECUSTUMERDETAIL="/custumer-detail/:id";
export const SEECUSTUMERDETAILPAS="/custumer-detail";
export const NEWMP ="/new-mp";
export const NEWPRODUCT ="/new-product";
export const NEWPACKAGE ="/new-package";
export const NEWORDER ="/new-order";
export const SEEALLORDERS ="/get-allorders";
export const SEEALLMP="/get-allmp";
export const SEEMPDETAIL="/mp-detail/:id";
export const SEEMPDETAILPAS="/mp-detail";
export const SEEALLPRODUCTS="/get-products";
export const SEEPRODUCTDETAIL="/product-detail/:id";
export const SEEPRODUCTDETAILPAS="/product-detail";
export const SEEALLPACKAGES="/get-allpackages";
export const SEEPACKAGESDETAIL="/packages-detail/:id";
export const SEEPACKAGESDETAILPAS="/packages-detail";
export const SEEORDERDETAIL="/order-detail/:id";
export const SEEORDERDETAILPAS="/order-detail";
export const SEECALENDAR="/dates";
export const NEWROUTE="/new-route";
export const SEEROUTEDETAIL="/route-detail/:id"
export const SEEROUTEDETAILPAS="/route-detail"